export const DESTINATION_VIBES: Record<string, ReadonlySet<string>> = {
  CUN: new Set(['tropical', 'beach', 'big_city', 'nightlife', 'romantic']),
  SJU: new Set(['tropical', 'beach', 'big_city', 'cultural', 'nightlife']),
  PUJ: new Set(['tropical', 'beach', 'romantic']),
  MBJ: new Set(['tropical', 'beach', 'romantic', 'adventure']),
  NAS: new Set(['tropical', 'beach', 'romantic']),
  GCM: new Set(['tropical', 'beach', 'romantic']),
  BGI: new Set(['tropical', 'beach', 'romantic', 'cultural']),
  ANU: new Set(['tropical', 'beach', 'romantic']),
  STT: new Set(['tropical', 'beach', 'romantic', 'adventure']),
  STX: new Set(['tropical', 'beach', 'adventure']),
  SXM: new Set(['tropical', 'beach', 'nightlife', 'romantic']),
  PLS: new Set(['tropical', 'beach', 'romantic']),
  SJD: new Set(['tropical', 'beach', 'romantic', 'adventure']),
  PVR: new Set(['tropical', 'beach', 'romantic', 'nightlife']),
  CTG: new Set(['tropical', 'beach', 'cultural', 'romantic']),
  SDQ: new Set(['tropical', 'beach', 'big_city']),
  ZIH: new Set(['tropical', 'beach', 'romantic']),
  HAV: new Set(['tropical', 'beach', 'cultural']),
  MCO: new Set(['beach', 'big_city', 'adventure']),
  MIA: new Set(['beach', 'big_city', 'nightlife', 'tropical']),
  FLL: new Set(['beach', 'tropical']),
  TPA: new Set(['beach']),
  RSW: new Set(['beach']),
  SAN: new Set(['beach', 'big_city', 'foodie']),
  HNL: new Set(['tropical', 'beach', 'romantic', 'adventure']),
  JFK: new Set(['big_city', 'cultural', 'foodie', 'nightlife']),
  LGA: new Set(['big_city', 'cultural', 'foodie', 'nightlife']),
  EWR: new Set(['big_city', 'cultural', 'foodie', 'nightlife']),
  LAX: new Set(['big_city', 'beach', 'cultural', 'foodie', 'nightlife']),
  ORD: new Set(['big_city', 'cultural', 'foodie']),
  LAS: new Set(['nightlife', 'big_city', 'adventure']),
  ATL: new Set(['big_city', 'cultural', 'foodie']),
  DFW: new Set(['big_city', 'foodie']),
  DEN: new Set(['mountain', 'adventure', 'big_city']),
  SEA: new Set(['big_city', 'cultural', 'foodie', 'mountain']),
  BOS: new Set(['big_city', 'cultural', 'foodie']),
  SFO: new Set(['big_city', 'cultural', 'foodie']),
  MSY: new Set(['cultural', 'foodie', 'nightlife']),
  BNA: new Set(['cultural', 'nightlife', 'foodie']),
  AUS: new Set(['cultural', 'nightlife', 'foodie']),
  PDX: new Set(['foodie', 'cultural']),
  PHX: new Set(['adventure', 'mountain']),
  LHR: new Set(['big_city', 'cultural', 'foodie']),
  CDG: new Set(['big_city', 'cultural', 'foodie', 'romantic']),
  FCO: new Set(['big_city', 'cultural', 'foodie', 'romantic']),
  BCN: new Set(['big_city', 'beach', 'cultural', 'foodie', 'nightlife']),
  MAD: new Set(['big_city', 'cultural', 'foodie', 'nightlife']),
  AMS: new Set(['big_city', 'cultural', 'nightlife']),
  LIS: new Set(['big_city', 'cultural', 'foodie', 'beach', 'romantic']),
  ATH: new Set(['cultural', 'beach', 'foodie', 'romantic']),
  IST: new Set(['big_city', 'cultural', 'foodie']),
  DUB: new Set(['cultural', 'foodie']),
  CPH: new Set(['cultural', 'foodie', 'big_city']),
  PRG: new Set(['cultural', 'romantic', 'nightlife']),
  BUD: new Set(['cultural', 'nightlife', 'romantic']),
  KEF: new Set(['adventure', 'romantic']),
  GIG: new Set(['beach', 'big_city', 'cultural', 'nightlife', 'tropical']),
  GRU: new Set(['big_city', 'cultural', 'foodie']),
  EZE: new Set(['big_city', 'cultural', 'foodie', 'nightlife']),
  BOG: new Set(['big_city', 'cultural', 'foodie', 'mountain']),
  MDE: new Set(['big_city', 'cultural', 'foodie', 'mountain']),
  LIM: new Set(['big_city', 'cultural', 'foodie']),
  SJO: new Set(['adventure', 'tropical', 'beach']),
  PTY: new Set(['big_city', 'tropical', 'beach']),
  BZE: new Set(['tropical', 'beach', 'adventure']),
  BKK: new Set(['big_city', 'cultural', 'foodie', 'nightlife', 'tropical']),
  DPS: new Set(['tropical', 'beach', 'cultural', 'romantic', 'adventure']),
  SIN: new Set(['big_city', 'cultural', 'foodie']),
  HKG: new Set(['big_city', 'cultural', 'foodie']),
  NRT: new Set(['big_city', 'cultural', 'foodie']),
  HND: new Set(['big_city', 'cultural', 'foodie']),
  ICN: new Set(['big_city', 'cultural', 'foodie']),
  DXB: new Set(['big_city', 'beach']),
  CMB: new Set(['tropical', 'beach', 'cultural']),
  SYD: new Set(['big_city', 'beach', 'cultural', 'foodie']),
  AKL: new Set(['adventure', 'cultural']),
  CPT: new Set(['big_city', 'beach', 'adventure', 'cultural', 'foodie']),
  NBO: new Set(['adventure', 'cultural']),
  RAK: new Set(['cultural', 'foodie', 'romantic']),
  CAI: new Set(['cultural', 'big_city']),
  HRG: new Set(['beach', 'tropical']),
  SSH: new Set(['beach', 'tropical']),
};
