import type { CanonicalVibe } from "@/lib/trip-types";

// Canonical vibe taxonomy. Vocabulary is exactly CANONICAL_VIBES — enforced at
// compile time by CanonicalVibe and at test time by
// vibe-vocabulary.guard.test.ts. Keys are the codes TravelPayouts returns:
// mostly airport codes, plus metro CITY codes (NYC, CHI, ORL, ...) which TP
// uses for its most popular destinations. Entry order matters: the curated
// filler breaks overlap ties by insertion order, so new entries go at the end.
export const DESTINATION_VIBES: Record<string, ReadonlySet<CanonicalVibe>> = {
  CUN: new Set<CanonicalVibe>(['tropical', 'beach', 'big_city', 'nightlife', 'romantic', 'family']),
  SJU: new Set<CanonicalVibe>(['tropical', 'beach', 'big_city', 'cultural', 'nightlife']),
  PUJ: new Set<CanonicalVibe>(['tropical', 'beach', 'romantic', 'family']),
  MBJ: new Set<CanonicalVibe>(['tropical', 'beach', 'romantic', 'adventure']),
  NAS: new Set<CanonicalVibe>(['tropical', 'beach', 'romantic', 'family']),
  GCM: new Set<CanonicalVibe>(['tropical', 'beach', 'romantic', 'family']),
  BGI: new Set<CanonicalVibe>(['tropical', 'beach', 'romantic', 'cultural']),
  ANU: new Set<CanonicalVibe>(['tropical', 'beach', 'romantic']),
  STT: new Set<CanonicalVibe>(['tropical', 'beach', 'romantic', 'adventure']),
  STX: new Set<CanonicalVibe>(['tropical', 'beach', 'adventure']),
  SXM: new Set<CanonicalVibe>(['tropical', 'beach', 'nightlife', 'romantic']),
  PLS: new Set<CanonicalVibe>(['tropical', 'beach', 'romantic', 'family']),
  SJD: new Set<CanonicalVibe>(['tropical', 'beach', 'romantic', 'adventure']),
  PVR: new Set<CanonicalVibe>(['tropical', 'beach', 'romantic', 'nightlife']),
  CTG: new Set<CanonicalVibe>(['tropical', 'beach', 'cultural', 'romantic']),
  SDQ: new Set<CanonicalVibe>(['tropical', 'beach', 'big_city']),
  ZIH: new Set<CanonicalVibe>(['tropical', 'beach', 'romantic']),
  HAV: new Set<CanonicalVibe>(['tropical', 'beach', 'cultural']),
  MCO: new Set<CanonicalVibe>(['beach', 'big_city', 'adventure', 'family']),
  MIA: new Set<CanonicalVibe>(['beach', 'big_city', 'nightlife', 'tropical']),
  FLL: new Set<CanonicalVibe>(['beach', 'tropical', 'family']),
  TPA: new Set<CanonicalVibe>(['beach', 'family']),
  RSW: new Set<CanonicalVibe>(['beach', 'family']),
  SAN: new Set<CanonicalVibe>(['beach', 'big_city', 'foodie', 'family']),
  HNL: new Set<CanonicalVibe>(['tropical', 'beach', 'romantic', 'adventure', 'family']),
  JFK: new Set<CanonicalVibe>(['big_city', 'cultural', 'foodie', 'nightlife', 'romantic']),
  LGA: new Set<CanonicalVibe>(['big_city', 'cultural', 'foodie', 'nightlife', 'romantic']),
  EWR: new Set<CanonicalVibe>(['big_city', 'cultural', 'foodie', 'nightlife', 'romantic']),
  LAX: new Set<CanonicalVibe>(['big_city', 'beach', 'cultural', 'foodie', 'nightlife']),
  ORD: new Set<CanonicalVibe>(['big_city', 'cultural', 'foodie', 'nightlife']),
  LAS: new Set<CanonicalVibe>(['nightlife', 'big_city', 'adventure']),
  ATL: new Set<CanonicalVibe>(['big_city', 'cultural', 'foodie']),
  DFW: new Set<CanonicalVibe>(['big_city', 'foodie']),
  DEN: new Set<CanonicalVibe>(['mountains', 'adventure', 'big_city', 'winter']),
  SEA: new Set<CanonicalVibe>(['big_city', 'cultural', 'foodie', 'mountains']),
  BOS: new Set<CanonicalVibe>(['big_city', 'cultural', 'foodie']),
  SFO: new Set<CanonicalVibe>(['big_city', 'cultural', 'foodie']),
  MSY: new Set<CanonicalVibe>(['cultural', 'foodie', 'nightlife']),
  BNA: new Set<CanonicalVibe>(['cultural', 'nightlife', 'foodie']),
  AUS: new Set<CanonicalVibe>(['cultural', 'nightlife', 'foodie']),
  PDX: new Set<CanonicalVibe>(['foodie', 'cultural']),
  PHX: new Set<CanonicalVibe>(['adventure', 'mountains']),
  LHR: new Set<CanonicalVibe>(['big_city', 'cultural', 'foodie', 'nightlife']),
  CDG: new Set<CanonicalVibe>(['big_city', 'cultural', 'foodie', 'romantic']),
  FCO: new Set<CanonicalVibe>(['big_city', 'cultural', 'foodie', 'romantic']),
  BCN: new Set<CanonicalVibe>(['big_city', 'beach', 'cultural', 'foodie', 'nightlife']),
  MAD: new Set<CanonicalVibe>(['big_city', 'cultural', 'foodie', 'nightlife']),
  AMS: new Set<CanonicalVibe>(['big_city', 'cultural', 'nightlife']),
  LIS: new Set<CanonicalVibe>(['big_city', 'cultural', 'foodie', 'beach', 'romantic']),
  ATH: new Set<CanonicalVibe>(['cultural', 'beach', 'foodie', 'romantic']),
  IST: new Set<CanonicalVibe>(['big_city', 'cultural', 'foodie']),
  DUB: new Set<CanonicalVibe>(['cultural', 'foodie']),
  CPH: new Set<CanonicalVibe>(['cultural', 'foodie', 'big_city', 'family']),
  PRG: new Set<CanonicalVibe>(['cultural', 'romantic', 'nightlife']),
  BUD: new Set<CanonicalVibe>(['cultural', 'nightlife', 'romantic']),
  KEF: new Set<CanonicalVibe>(['adventure', 'romantic', 'mountains', 'winter']),
  GIG: new Set<CanonicalVibe>(['beach', 'big_city', 'cultural', 'nightlife', 'tropical']),
  GRU: new Set<CanonicalVibe>(['big_city', 'cultural', 'foodie']),
  EZE: new Set<CanonicalVibe>(['big_city', 'cultural', 'foodie', 'nightlife']),
  BOG: new Set<CanonicalVibe>(['big_city', 'cultural', 'foodie', 'mountains']),
  MDE: new Set<CanonicalVibe>(['big_city', 'cultural', 'foodie', 'mountains', 'nightlife']),
  LIM: new Set<CanonicalVibe>(['big_city', 'cultural', 'foodie']),
  SJO: new Set<CanonicalVibe>(['adventure', 'tropical', 'beach', 'mountains']),
  PTY: new Set<CanonicalVibe>(['big_city', 'tropical', 'beach']),
  BZE: new Set<CanonicalVibe>(['tropical', 'beach', 'adventure']),
  BKK: new Set<CanonicalVibe>(['big_city', 'cultural', 'foodie', 'nightlife', 'tropical']),
  DPS: new Set<CanonicalVibe>(['tropical', 'beach', 'cultural', 'romantic', 'adventure']),
  SIN: new Set<CanonicalVibe>(['big_city', 'cultural', 'foodie', 'family']),
  HKG: new Set<CanonicalVibe>(['big_city', 'cultural', 'foodie']),
  NRT: new Set<CanonicalVibe>(['big_city', 'cultural', 'foodie']),
  HND: new Set<CanonicalVibe>(['big_city', 'cultural', 'foodie']),
  ICN: new Set<CanonicalVibe>(['big_city', 'cultural', 'foodie']),
  DXB: new Set<CanonicalVibe>(['big_city', 'beach', 'family']),
  CMB: new Set<CanonicalVibe>(['tropical', 'beach', 'cultural']),
  SYD: new Set<CanonicalVibe>(['big_city', 'beach', 'cultural', 'foodie']),
  AKL: new Set<CanonicalVibe>(['adventure', 'cultural']),
  CPT: new Set<CanonicalVibe>(['big_city', 'beach', 'adventure', 'cultural', 'foodie', 'mountains']),
  NBO: new Set<CanonicalVibe>(['adventure', 'cultural']),
  RAK: new Set<CanonicalVibe>(['cultural', 'foodie', 'romantic']),
  CAI: new Set<CanonicalVibe>(['cultural', 'big_city']),
  HRG: new Set<CanonicalVibe>(['beach', 'tropical']),
  SSH: new Set<CanonicalVibe>(['beach', 'tropical']),
  // ── NEW: genuine snow/ski winter destinations (back the Winter Escapade
  // chip) + Málaga, which carries NO winter tag (warm-weather; spec bans it).
  // YVR carries NO 'beach' tag (Jose, 2026-07-12: "vancouver is not a beach
  // city destination") — which is why beach+winter is honestly impossible. ──
  YVR: new Set<CanonicalVibe>(['mountains', 'winter', 'big_city', 'foodie', 'family']),
  SLC: new Set<CanonicalVibe>(['mountains', 'winter', 'adventure', 'family']),
  ZRH: new Set<CanonicalVibe>(['mountains', 'winter', 'big_city', 'cultural']),
  GVA: new Set<CanonicalVibe>(['mountains', 'winter', 'romantic', 'cultural']),
  MUC: new Set<CanonicalVibe>(['big_city', 'cultural', 'foodie', 'winter']),
  AGP: new Set<CanonicalVibe>(['beach', 'cultural', 'foodie']),
  // ── NEW: TravelPayouts metro CITY codes (TP's most-returned destinations) ──
  NYC: new Set<CanonicalVibe>(['big_city', 'cultural', 'foodie', 'nightlife', 'romantic']),
  CHI: new Set<CanonicalVibe>(['big_city', 'cultural', 'foodie', 'nightlife']),
  ORL: new Set<CanonicalVibe>(['family', 'adventure']),
  WAS: new Set<CanonicalVibe>(['big_city', 'cultural', 'family']),
  PAR: new Set<CanonicalVibe>(['romantic', 'cultural', 'foodie', 'big_city']),
  LON: new Set<CanonicalVibe>(['big_city', 'cultural', 'foodie', 'nightlife']),
  YTO: new Set<CanonicalVibe>(['big_city', 'cultural', 'foodie', 'family']),
  HOU: new Set<CanonicalVibe>(['big_city', 'foodie', 'family']),
  PIT: new Set<CanonicalVibe>(['big_city', 'cultural']),
  MOW: new Set<CanonicalVibe>(['big_city', 'cultural', 'nightlife', 'winter']),
  RDU: new Set<CanonicalVibe>(['big_city', 'foodie']),
  ANC: new Set<CanonicalVibe>(['mountains', 'adventure', 'winter']),
  BEG: new Set<CanonicalVibe>(['big_city', 'nightlife', 'cultural']),
};
